### ISSUE TITLE
Controller: user

### ISSUE THREAD

**Issue by saloonregular** [beetlefinder/go-server#3]
# Controller: user

 **Branch `feature/controllers`**
After #5 complete

## Issue overview

Create `controller` package. Create user controller with `create` and `get` methods.
Describe HTTP methods to project wiki.

## Example

```go
type User struct{}

func (User) Create(ctx gocontext.Context) gin.HandlerFunc {
	return func(c *gin.Context) {
		// Logic here.
	}
}

func (User) Get(ctx gocontext.Context) gin.HandlerFunc {
	// Another logic here.
}
```

**Comment by KozlovDM** [comment]
It was mistake. Issue #9
